### ISSUE TITLE
New pgs-password branch

### ISSUE THREAD

**Issue by gleu** [dalibo/pgshark#3]
The pgs-password branch adds a new utility, called pgs-password. This utility tracks connections to get username and password. Obviously, that only works with a clear-text password authentication method. Adding this script will make it obvious that you can sniff password with this authentication method and, hence, that it shouldn't be used.

**Comment by ioguix** [comment]
Same story than for #4, latest patch should do the trick.

Can we drop these branches ?

**Comment by gleu** [comment]
Sure, go ahead :)

**Comment by ioguix** [comment]
Done.

Thank you!
