### ISSUE TITLE
New pgs-connections branch

### ISSUE THREAD

**Issue by gleu** [dalibo/pgshark#4]
The pgs-connections adds a new utility called pgs-connections. This utility prints the duration between the first message of a connection (StartupMessage) and the state ReadyForQuery. The idea is to check out how much time it takes to be ready to send queries on a new connection.

Not sure this is the best way to code this, but I guess it still has its usefulness.

**Comment by ioguix** [comment]
Hi Guillaume,

I believe the following patch allows you to do the exact same thing with existing pgs-debug, by filtering what you want to see in the output: ebb7e723566da3fdd80ab7cc79612b3af14b6e88

Moreover, if you need a special formating on output, see 0dddeb3fa431712a4471109068a1a3bb3d16a2c4

So if you agree, I think we should drop this branch.

Regards,

**Comment by gleu** [comment]
Agreed, drop it.

**Comment by ioguix** [comment]
Done. Thank you!
