### ISSUE TITLE
cannot to reduce a size of pgshark log

### ISSUE THREAD

**Issue by okbob** [dalibo/pgshark#5]
pgshark logs every message, every communication. Sometimes the logged communication is pretty big. The possibility to reduce size of result can be nice - skip content of CopyData, DataRow, Describe, RowDescription/ Skip frequently used protocol events that are not visible from application level - Bind, BindComplete, DataRow, Parse, ParseComplete,  Sync.

See http://okbob.blogspot.dk/2015/03/long-term-monitoring-communication.html

**Comment by ioguix** [comment]
Hi,

Thank you for posting this here :)
In the meantime, I just forgot about your blog post, sorry about that.

I might be able to work pretty soon!

Cheers,

**Comment by ioguix** [comment]
Hi,

I just committed a patch which I believe answers this feature request. See commit ebb7e723566da3fdd80ab7cc79612b3af14b6e88

Cheers,

**Comment by okbob** [comment]
great, thank you
