### ISSUE TITLE
append timestamp to logged event

### ISSUE THREAD

**Issue by okbob** [dalibo/pgshark#6]
I had to append timestamp to any logged event with external application. Can be nice do this work with pgshark option. Another options for log line prefix can be user, database, application_name

See http://okbob.blogspot.dk/2015/03/long-term-monitoring-communication.html

**Comment by ioguix** [comment]
Hi,

Thank you for reporting this here.

About timestamp, I think I have such patch floating around. Moreover, the prefix stuff is already done in pgs-query, it should be easy to port this piece of code to pgs-debug.

I'll try to have a look on this soon.

**Comment by ioguix** [comment]
Hi,

I believe my last commit answer your need, see 0dddeb3fa431712a4471109068a1a3bb3d16a2c4.

I added a bunch of parameter, but not user, database, application_name, as they need to keep track of the sessions and I'm a bit lazy tonight. I'll add this in a future patch. However, note that without the first message from the frontend, these parameters can not be shown.

See pgs-debug docs for more info.

Enjoy,

**Comment by okbob** [comment]
2015-11-05 0:53 GMT+01:00 Jehan-Guillaume (ioguix) de Rorthais <
notifications@github.com>:

> Hi,
>
> I believe my last commit answer your need, see 0dddeb3
> <https://github.com/dalibo/pgshark/commit/0dddeb3fa431712a4471109068a1a3bb3d16a2c4>
> .
>
> I added a bunch of parameter, but not user, database, application_name, as
> they need to keep track of the sessions and I'm a bit lazy tonight. I'll
> add this in a future patch. However, note that without the first message
> from the frontend, these parameters can not be shown.
>

you can hold these parameters in session memory

Pavel

**Comment by ioguix** [comment]
What you mean "in session memory" ?

**Comment by okbob** [comment]
2015-11-05 8:42 GMT+01:00 Jehan-Guillaume (ioguix) de Rorthais <
notifications@github.com>:

> What you mean "in session memory" ?
>

In this case, pgshark memory

Pavel

**Comment by ioguix** [comment]
Done, I finally took some time to add them.

Cheers,

**Comment by okbob** [comment]
Thank you

Pavel
